// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NETD3202Lab5_1.Models;

namespace NETD3202Lab5_1.Migrations
{
    [DbContext(typeof(VideoGameContext))]
    [Migration("20201206211429_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NETD3202Lab5_1.Models.VideoGame", b =>
                {
                    b.Property<int>("videoGameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("videoGameGenre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoGameName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoGamePlatform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoGameRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("videoGameRelease")
                        .HasColumnType("int");

                    b.HasKey("videoGameID");

                    b.ToTable("VideoGames");
                });

            modelBuilder.Entity("NETD3202Lab5_1.Models.VideoGameDetails", b =>
                {
                    b.Property<int>("videoGameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("videoGameDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("videoGameID1")
                        .HasColumnType("int");

                    b.HasKey("videoGameID");

                    b.HasIndex("videoGameID1");

                    b.ToTable("AdditionalGameDetails");
                });

            modelBuilder.Entity("NETD3202Lab5_1.Models.VideoGameDetails", b =>
                {
                    b.HasOne("NETD3202Lab5_1.Models.VideoGame", "VideoGame")
                        .WithMany()
                        .HasForeignKey("videoGameID1");
                });
#pragma warning restore 612, 618
        }
    }
}
